import {SingleProgram} from './types';

export const mockedPrograms: SingleProgram[] = [
    {
        midill: 'STOD2',
        midill_heiti: 'Stöð 2',
        dagsetning: '2023-08-23T00:00:00Z',
        upphaf: '2023-08-23T07:55:00Z',
        titill: 'Heimsókn 11',
        isltitill: 'Heimsókn',
        undirtitill: 'Margrét Ýr Ingimarsdóttir',
        seria: 11,
        thattur: 6,
        thattafjoldi: 8,
        birta_thatt: 1,
        opin: 0,
        beint: 0,
        frumsyning: 0,
        framundan_i_beinni: 0,
        flokkur: 'Lífsstíll',
        adalhlutverk: '',
        leikstjori: '',
        ar: '',
        bannad: 'Green',
        frelsi: 0,
        netdagar: 0,
        lysing: 'Í næsta þætti af Heimsókn bankar Sindri uppá hjá Margréti Ýri sem býr í fallegu húsi í Garðabænum þar sem allt hefur verið tekið í gegn af innanhússarkitektinum Berglindi Berndsen. Ekki missa af stórskemmtilegri Margréti í Heimsókn.',
        slott: 25,
        slotlengd: '00:25',
    },
    {
        midill: 'STOD2',
        midill_heiti: 'Stöð 2',
        dagsetning: '2023-08-23T00:00:00Z',
        upphaf: '2023-08-23T09:10:00Z',
        titill: 'Bold and the Beautiful',
        isltitill: 'Bold and the Beautiful',
        undirtitill: 'Bold and the Beautiful',
        seria: 34,
        thattur: 8668,
        thattafjoldi: 749,
        birta_thatt: 1,
        opin: 0,
        beint: 0,
        frumsyning: 1,
        framundan_i_beinni: 0,
        flokkur: 'Drama,Romance',
        adalhlutverk: '',
        leikstjori: '',
        ar: '',
        bannad: 'Green',
        frelsi: 0,
        netdagar: 28,
        lysing: 'Forrester-fjölskyldan er leiðandi í tískuheiminum en með miklum vinsældum fylgir líka mikil ábyrgð og pressa á að standa sig. Endalaus valdabarátta og erjur utan sem innan fyrirtækisins setja  stundum mark sitt starfsemina og ekki hjálpa flóknu fjölskyldutengslin til sér í lagi þegar Spencer klanið fléttast inn í daglegt líf þeirra.',
        slott: 25,
        slotlengd: '00:25',
    },
];
